# AUTH GROUP
GET http://localhost:8085/api/v2/auth/login HTTP/1.1
###

# URL GROUP
# create url
POST http://localhost:8085/api/v2/url HTTP/1.1
Content-Type: application/json

{
    "url": "https://name.com"
}
###

# get url
GET http://localhost:8085/api/v2/url HTTP/1.1
###

# get url by short url
GET http://localhost:8085/api/v2/url/short_url/shortUrl HTTP/1.1
###

# get url statistic
GET http://localhost:8085/api/v2/url/statistic HTTP/1.1
###

# update url
PUT http://localhost:8085/api/v2/url/11 HTTP/1.1
Content-Type: application/json

{
    "url": "https://name.com",
    "shortUrl": "shortUrl"
}
###

# delete url
DELETE http://localhost:8085/api/v2/url/30 HTTP/1.1
###

