# get user
GET http://localhost:8085/api/v2/user/1 HTTP/1.1
###

# update user
PUT http://localhost:8085/api/v2/user/1 HTTP/1.1
Content-Type: application/json

{
    "id": "1",
    "username": "admin",
    "name": "new admin",
    "email": "admin@gmail.com"
}
###

# update password
PUT http://localhost:8085/api/v2/user/password/1 HTTP/1.1
Content-Type: application/json

{
    "currentPassword": "1234",
    "newPassword": "1234"
}
###